const http=require('http');
const fs=require('fs');
const path=require('path');
const WebSocket=require('ws');
const PORT=process.env.PORT||3000;
const universes={
"Mushoku Tensei":["Rudeus Greyrat","Sylphiette","Eris Boreas Greyrat","Roxy Migurdia"],"Tensura Slime":["Rimuru Tempest","Milim Nava","Benimaru","Shion"],"Re:Zero":["Subaru Natsuki","Emilia","Rem","Ram"],"Hunter x Hunter":["Gon Freecss","Killua Zoldyck","Kurapika","Hisoka"],"JoJo (Parties 1-6)":["Jonathan Joestar","Joseph Joestar","Jotaro Kujo","Josuke Higashikata","Giorno Giovanna","Jolyne Cujoh"],"Chainsaw Man":["Denji","Power","Makima","Aki Hayakawa"],"Jujutsu Kaisen":["Yuji Itadori","Megumi Fushiguro","Nobara Kugisaki","Satoru Gojo"],"Undertale / Deltarune":["Frisk","Sans","Papyrus","Kris","Susie","Ralsei"],"Genshin Impact":["Lumine","Aether","Paimon","Raiden Shogun"],"Honkai: Star Rail":["Trailblazer","March 7th","Dan Heng","Kafka"],"Zenless Zone Zero":["Wise","Belle","Anby Demara","Ellen Joe"],"Demon Slayer":["Tanjiro Kamado","Nezuko Kamado","Zenitsu Agatsuma","Inosuke Hashibira"],"SNK / Attack on Titan":["Eren Yeager","Mikasa Ackerman","Armin Arlert","Levi Ackerman"],"Seven Deadly Sins":["Meliodas","Elizabeth Liones","Ban","King"],"Death Note":["Light Yagami","L","Misa Amane","Ryuk"],"Bleach":["Ichigo Kurosaki","Rukia Kuchiki","Orihime Inoue","Byakuya Kuchiki"],"KonoSuba":["Kazuma Satou","Aqua","Megumin","Darkness"]};
const skillSets={
"Mushoku Tensei":["Incantation silencieuse","Détection magique","Lame de mana","Magie de pierre"],"Tensura Slime":["Gluttony","Barrière multicouche","Aura de domination","Prédation"],"Re:Zero":["Retour par la mort","Magie Yin","Autorité mystérieuse","Renforcement spirituel"],"Hunter x Hunter":["Renforcement du Nen","Bungee Gum","Jajanken","Godspeed"],"JoJo (Parties 1-6)":["Hamon","Star Platinum","Crazy Diamond","Golden Experience","Stone Free"],"Chainsaw Man":["Transformation démoniaque","Contrat démoniaque","Tranchage brutal","Régénération sanguine"],"Jujutsu Kaisen":["Énergie occulte","Extension de territoire","Technique innée","Black Flash"],"Undertale / Deltarune":["Garde","Âme déterminée","Gaster Blaster","Magie de l'âme"],"Genshin Impact":["Vision élémentaire","Réaction élémentaire","Déchaînement élémentaire","Compétence élémentaire"],"Honkai: Star Rail":["Technique de voie","Ultime de voie","Frappe de rupture","Effet de faiblesse"],"Zenless Zone Zero":["Esquive parfaite","Chaîne d'attaque","Attribut anomalie","Ultime d'agent"],"Demon Slayer":["Souffle de l'eau","Souffle du tonnerre","Danse du dieu du feu","Respiration de la bête"],"SNK / Attack on Titan":["Manœuvre tridimensionnelle","Lame anti-titan","Transformation titan","Frappe ciblée"],"Seven Deadly Sins":["Full Counter","Chastiefol","Snatch","Pouvoir sacré"],"Death Note":["Nom dans le Death Note","Observation","Manipulation psychologique","Œil du shinigami"],"Bleach":["Shunpo","Zanpakutō","Bankai","Getsuga Tenshō"],"KonoSuba":["Explosion","Steal","Soin divin","Darkness — provocation"]};
const passives=["Berserker : plus les PV baissent, plus les dégâts augmentent","Gardien : la première attaque reçue est réduite de moitié","Instinct : une chance d'esquiver une attaque","Dernier souffle : une fois par combat, survit à 1 PV","Régénération : récupère quelques PV au début de son tour","Adaptation : après avoir subi une compétence, gagne un bonus temporaire","Précognition : le premier tour adverse inflige moins de dégâts","Malédiction : la dernière attaque peut appliquer des dégâts bonus"];
const chars=Object.entries(universes).flatMap(([u,cs])=>cs.map(name=>({name,universe:u})));
const rooms=new Map();
function rand(a){return a[Math.floor(Math.random()*a.length)]}
function code(){let c;do c=Math.random().toString(36).slice(2,7).toUpperCase();while(rooms.has(c));return c}
function send(ws,msg){if(ws.readyState===1)ws.send(JSON.stringify(msg))}
function playersView(r){return r.players.map(p=>({id:p.id,name:p.name}))}
function broadcast(r,msg){r.players.forEach(p=>send(p.ws,msg))}
function selectedPool(list){const us=list&&list.length?list:Object.keys(skillSets);return us.flatMap(u=>skillSets[u]||[])}
function battlePublic(r){return {players:r.players.map(p=>({id:p.id,name:p.name,hp:p.hp,power:p.power,skills:p.id===r.startedBy?[...p.skills]:[]})),turn:r.game.turn,over:r.game.over,log:r.game.log}}
function battleStateFor(r,viewer){return {players:r.players.map(p=>({id:p.id,name:p.name,hp:p.hp,power:p.power,skills:p.id===viewer?[...p.skills]:[],passive:p.id===viewer?p.passive:'Passif secret'})),turn:r.game.turn,over:r.game.over,log:r.game.log}}
function sendBattle(r){r.players.forEach(p=>send(p.ws,{type:'battle_state',state:battleStateFor(r,p.id)}))}
function startBattle(r,selected){const pool=selectedPool(selected);r.game={type:'battle',turn:0,over:false,log:'⚔️ Le combat commence !'};r.players.forEach((p,i)=>{p.hp=100;p.power=65+Math.floor(Math.random()*31);p.skills=[...pool].sort(()=>Math.random()-.5).slice(0,4);p.passive=rand(passives);p.usedPassive=false;p.guard=false;p.id=i});r.started=true;sendBattle(r);}
function alive(r){return r.players.filter(p=>p.hp>0)}
function nextTurn(r,i){let n=(i+1)%r.players.length,c=0;while(r.players[n].hp<=0&&c<r.players.length){n=(n+1)%r.players.length;c++}r.game.turn=n}
function battleAction(r,p,idx){if(r.game.over||r.game.turn!==p.id||p.hp<=0)return;const target=rand(alive(r).filter(x=>x.id!==p.id));if(!target)return;const skill=p.skills[idx];if(!skill)return;let damage=Math.max(8,Math.min(58,Math.round(p.power*.42+Math.random()*24)));if(p.hp<35)damage+=10;if(target.guard){damage=Math.round(damage*.5);target.guard=false}if(!p.usedPassive&&p.passive.startsWith('Instinct')&&Math.random()<.12){p.usedPassive=true;damage=0}if(!p.usedPassive&&p.passive.startsWith('Dernier souffle')&&target.hp-damage<=0){damage=Math.max(0,target.hp-1);p.usedPassive=true}target.hp=Math.max(0,target.hp-damage);let log=`🎯 ${p.name} utilise « ${skill} » sur ${target.name} : ${damage} dégâts.`;if(p.passive.startsWith('Régénération'))p.hp=Math.min(100,p.hp+8);if(target.hp===0)log+=` 💥 ${target.name} est K.O.`;r.game.log+=`\nTour ${p.id+1} — ${log}`;if(alive(r).length<=1){r.game.over=true;const w=alive(r)[0];r.game.log+=w?`\n\n🏆 ${w.name} remporte le combat !`:'\n\n💀 Égalité.'}else nextTurn(r,p.id);sendBattle(r)}
function startGuess(r){r.game={type:'guess',turn:0,over:false,scores:[0,0],questions:[]};r.players.forEach(p=>{p.secret=rand(chars);});r.players.forEach(p=>send(p.ws,{type:'guess_start',myCharacter:p.secret.name,turn:r.game.turn}));}
function other(r,id){return r.players.find(p=>p.id!==id)}
function route(ws,m){const p=ws.player;if(m.type==='create_room'){if(p.room) return send(ws,{type:'error',message:'Tu es déjà dans une salle.'});const c=code(),r={code:c,mode:m.mode,hostId:p.id,players:[],started:false,game:null};rooms.set(c,r);p.room=r;p.name=String(m.name||'Joueur').slice(0,24);r.players.push(p);send(ws,{type:'room_created',code:c,playerId:p.id,host:true,mode:r.mode,players:playersView(r)});return}
if(m.type==='join_room'){const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Salle introuvable.'});if(r.started)return send(ws,{type:'error',message:'La partie a déjà commencé.'});if(r.mode==='guess'&&r.players.length>=2)return send(ws,{type:'error',message:'Qui est-ce ? est limité à 2 joueurs.'});if(r.mode==='battle'&&r.players.length>=4)return send(ws,{type:'error',message:'Combat limité à 4 joueurs.'});p.room=r;p.name=String(m.name||'Joueur').slice(0,24);r.players.push(p);send(ws,{type:'room_joined',code:r.code,playerId:p.id,host:false,mode:r.mode,players:playersView(r)});broadcast(r,{type:'room_update',players:playersView(r)});return}
const r=p.room;if(!r)return send(ws,{type:'error',message:'Rejoins ou crée une salle.'});
if(m.type==='leave_room'){leave(p);return}
if(m.type==='start_battle'){if(r.hostId!==p.id||r.mode!=='battle')return; if(r.players.length<2)return send(ws,{type:'error',message:'Il faut au moins 2 joueurs.'});startBattle(r,m.universes);return}
if(m.type==='start_guess'){if(r.hostId!==p.id||r.mode!=='guess')return;if(r.players.length!==2)return send(ws,{type:'error',message:'Il faut exactement 2 joueurs.'});startGuess(r);return}
if(m.type==='battle_action'&&r.mode==='battle'&&r.game?.type==='battle'){battleAction(r,p,Number(m.skillIndex));return}
if(m.type==='guess_question'&&r.mode==='guess'&&r.game?.type==='guess'){if(r.game.over||r.game.turn!==p.id)return;const q=String(m.question||'').slice(0,180);const o=other(r,p.id);r.game.questions.push({from:p.id,text:q});send(o.ws,{type:'guess_question',question:q});send(ws,{type:'guess_state',turn:r.game.turn,log:'💬 Question envoyée.'});return}
if(m.type==='guess_answer'&&r.mode==='guess'&&r.game?.type==='guess'){const a=['Oui','Non','Je ne sais pas'].includes(m.answer)?m.answer:'Je ne sais pas';const o=other(r,p.id);send(o.ws,{type:'guess_answer',answer:a});r.game.turn=o.id;broadcast(r,{type:'guess_state',turn:r.game.turn,log:`🗣️ ${p.name} répond : ${a}`});return}
if(m.type==='guess_guess'&&r.mode==='guess'&&r.game?.type==='guess'){if(r.game.over||r.game.turn!==p.id)return;const guess=String(m.guess||'').trim().toLowerCase();const target=other(r,p.id).secret;if(guess===target.name.toLowerCase()){r.game.over=true;r.game.scores[p.id]+=1;broadcast(r,{type:'guess_end',message:`${p.name} a trouvé ${target.name} ! 🏆`});}else{r.game.turn=other(r,p.id).id;broadcast(r,{type:'guess_state',turn:r.game.turn,log:`❌ ${p.name} se trompe. Tour de ${other(r,p.id).name}.`});}}
}
function leave(p){const r=p.room;if(!r)return;const idx=r.players.indexOf(p);if(idx>=0)r.players.splice(idx,1);p.room=null;if(!r.players.length){rooms.delete(r.code);return}if(r.hostId===p.id)r.hostId=r.players[0].id;broadcast(r,{type:'room_update',players:playersView(r)});}
const server=http.createServer((req,res)=>{let file=req.url==='/'?'/anime_multiverse.html':req.url;file=file.split('?')[0];if(file==='/server.js'||file==='/package.json')return res.writeHead(403).end();const fp=path.join(__dirname,file);if(!fp.startsWith(__dirname)||!fs.existsSync(fp))return res.writeHead(404).end('Not found');const ext=path.extname(fp);const ct=ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'application/octet-stream';res.writeHead(200,{'Content-Type':ct});fs.createReadStream(fp).pipe(res)});
const wss=new WebSocket.Server({server});
let nextId=0;wss.on('connection',ws=>{const p={id:nextId++,ws,name:'Joueur'};ws.player=p;send(ws,{type:'hello',playerId:p.id});ws.on('message',b=>{try{route(ws,JSON.parse(b))}catch(e){send(ws,{type:'error',message:'Erreur serveur.'})}});ws.on('close',()=>{if(p.room)leave(p)})});
server.listen(PORT,()=>console.log(`Anime Multiverse : http://localhost:${PORT}`));
